// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDim6K7RLhQjaFpR8lH3NA2VjlaR6Vk3Os',
    appId: '1:720076865783:web:4f9fcbfa8a038b0b8793f2',
    messagingSenderId: '720076865783',
    projectId: 'kindness-network-27688',
    authDomain: 'kindness-network-27688.firebaseapp.com',
    databaseURL: 'https://kindness-network-27688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kindness-network-27688.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSZ8WkQeG1ZTaUd6BcvyCYGEiNVZhGsY4',
    appId: '1:720076865783:android:86ad4ed8543bc8778793f2',
    messagingSenderId: '720076865783',
    projectId: 'kindness-network-27688',
    databaseURL: 'https://kindness-network-27688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kindness-network-27688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jAquGpZyiSUONyy3JMwnhgDclh_LaJ4',
    appId: '1:720076865783:ios:84ef9677dbc1fd0b8793f2',
    messagingSenderId: '720076865783',
    projectId: 'kindness-network-27688',
    databaseURL: 'https://kindness-network-27688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kindness-network-27688.appspot.com',
    iosClientId: '720076865783-ptv71u7qvf22gmfr5hf31148asbb1jv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindnessNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7jAquGpZyiSUONyy3JMwnhgDclh_LaJ4',
    appId: '1:720076865783:ios:84ef9677dbc1fd0b8793f2',
    messagingSenderId: '720076865783',
    projectId: 'kindness-network-27688',
    databaseURL: 'https://kindness-network-27688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kindness-network-27688.appspot.com',
    iosClientId: '720076865783-ptv71u7qvf22gmfr5hf31148asbb1jv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindnessNetwork',
  );
}
